AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:

  # Build the API Gateway and setup an API Key
  ApiGatewayEndpoint:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: Prod
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          CreateUsagePlan: PER_API
          UsagePlanName: GatewayAuthorization

  # Setup the Lambda Function (You may want to change "ServerlessFunction" to something more meaningful)
  ServerlessFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: python3.8
      CodeUri: .
      Handler: lambda_function.lambda_handler
      Description:
      MemorySize: 128
      Timeout: 30
      Events:
        HttpApiAnyPathAnyMethod:
          # Wildcard all Paths and Methods (does not include "/")
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGatewayEndpoint
            Path: /{proxy+}
            Method: any
        HttpApiSpecificPathAndMethod:
          # Request to your endpoint must be post
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGatewayEndpoint
            Path: /your-api
            Method: POST

Outputs:
  ApiGateway:
    Description: "The URL is:"
    Value: !Sub "https://${ApiGatewayEndpoint}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  ApiKey:
    Description: "You can find your API Key in the AWS console: (Put in the request HEADER as 'x-api-key')"
    Value: !Sub "https://console.aws.amazon.com/apigateway/home?region=${AWS::Region}#/api-keys/${ApiGatewayEndpointApiKey}"
